### PR TITLE
Ontologies are optionally re-fetched on model creation

### LINKED ISSUE #121: If ontology fetch fails, return original object
[These lines](https://github.com/jataware/dojo/blob/af7c3852c525056caa14da6f52b54c573f9188fe/api/src/ontologies.py#L7-L55) should not return the failed response (in case of failure) but actually return the model/indicator so that registration doesn't fail completely. 

On model registration we get the following error if UAZ is down:

```
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='linking.cs.arizona.edu', port=80): Max retries exceeded with url: /v1/groundIndicator?maxHits=10&threshold=0.6&compositional=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc29b493ac0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2021-11-10 12:57:03,967 ERROR:    uvicorn.error - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./src/models.py", line 139, in register_model
    model_obj = ModelSchema.ModelMetadataSchema.parse_obj(model)
  File "pydantic/main.py", line 577, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for ModelMetadataSchema
__root__
  ModelMetadataSchema expected dict not NoneType (type=type_error)
```

### PR DESCRIPTION
**Pull request by brandomr**
When a model is cloned, we shouldn't have to re-send it to UAZ. This enables us to clone a model and retain the prior ontologies.

### CODE REVIEW

**Review by mattprintz — APPROVED** [review]
Looks good.

**Review by mattprintz — CHANGES_REQUESTED** [review]
Just tested this, and it doesn't work:

```
dojo-api         | 2021-10-12 20:41:23,096 ERROR:    uvicorn.error - Exception in ASGI application
dojo-api         | Traceback (most recent call last):
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
dojo-api         |     result = await app(self.scope, self.receive, self.send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
dojo-api         |     return await self.app(scope, receive, send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
dojo-api         |     await super().__call__(scope, receive, send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
dojo-api         |     await self.middleware_stack(scope, receive, send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
dojo-api         |     raise exc from None
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
dojo-api         |     await self.app(scope, receive, _send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
dojo-api         |     raise exc from None
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
dojo-api         |     await self.app(scope, receive, sender)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
dojo-api         |     await route.handle(scope, receive, send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
dojo-api         |     await self.app(scope, receive, send)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
dojo-api         |     response = await func(request)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
dojo-api         |     raw_response = await run_endpoint_function(
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
dojo-api         |     return await run_in_threadpool(dependant.call, **values)
dojo-api         |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
dojo-api         |     return await loop.run_in_executor(None, func, *args)
dojo-api         |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
dojo-api         |     result = self.fn(*self.args, **self.kwargs)
dojo-api         |   File "./src/models.py", line 165, in version_model
dojo-api         |     create_model(m, get_ontologies=False)
dojo-api         |   File "./src/models.py", line 39, in create_model
dojo-api         |     es.index(index="models", body=model, id=model_id)
dojo-api         | UnboundLocalError: local variable 'model' referenced before assignment
```

**Comment by brandomr** [comment]
This now also addresses #121

**Review by mattprintz — APPROVED** [review]
Looks good. Tests good. Thanks

**Pull request merged**
