### PR TITLE
Feature/rtk chirps

### PR DESCRIPTION
**Pull request by GoogleSheets**
### Description

- Addresses #106 

### Changes
- Uses the existing `CHIRPSController` class so changes are made to `self.name`, `self.stat` etc. prior to calling `self.run_model()`.
- `run_models()` is the processing entry point to `CHIRPSController` object.
- `set_days_of_year()` is called in `__init__` and sets self.days_of_year to an array of int. For CHIRPS this will be the first day of the month; for CHIRPS-GEFS this will be the 1st and 16th. 
- `run_models` then for each day of year loops the 3 statistics, downloads and processes the tiff.

### Output

A pandas DataFrame written to `results/chirps.csv` with the columns x, y, date, rainfall, anomaly, z-score.

The following (CHIRPS-GEF example) message is displayed when the script is finished:
```
INFO:root:Processing completed. Output to results/chirps.csv. Header and tail preview:
INFO:root:           x          y        date  rainfall  anomaly   z-score
0  33.537188  16.477245  01-01-2021       0.0      0.0 -0.011031
1  33.587095  16.477245  01-01-2021       0.0      0.0 -0.019770
2  33.637003  16.477245  01-01-2021       0.0      0.0  0.000000
3  33.686910  16.477245  01-01-2021       0.0      0.0 -0.016895
4  33.736818  16.477245  01-01-2021       0.0      0.0 -0.019790
INFO:root:                x        y        date  rainfall   anomaly    z-score
185455  49.757126  2.74443  01-16-2021  5.162117  5.162117 -13.052685
185456  49.807034  2.74443  01-16-2021  5.272977  5.272977 -12.957613
185457  49.856941  2.74443  01-16-2021  4.121017  4.121017 -14.470405
185458  49.906849  2.74443  01-16-2021  4.213909  4.213909 -14.488016
185459  49.956756  2.74443  01-16-2021  4.289431  4.289431 -15.104242
```

### Examples
CHIRPS:
`python run_chirps_tiff.py --name=CHIRPS --month=01 --year=2020 --bbox='[33.512234, 2.719907, 49.98171,16.501768]' --statistic=mm_data`

CHIRPS-GEFS:
`python run_chirps_tiff.py --name=CHIRPS-GEFS --month=01 --year=2021 --bbox='[33.512234, 2.719907, 49.98171,16.501768]' --statistic=mm_data --day_of_year=306`

### Notes

- output path is essentially hard coded to "results/"; that should probably be a constant of some sort.
- `run_chirps_tiff.py` requires `mixmasta`, but that is not normally installed in `dojo`. Therefore, testing was performed  by copying the script to a mixmasta docker container.

### CODE REVIEW

**Comment by brandomr** [comment]
@mlandsfeld does this seem about right to you?

**Comment by fmdavenport** [comment]
This looks correct to me, but I would want to see how the time series renders in CausMoS. What happens if a user requests the most recent date for CHIRPS-GEFS? Doe is just snap to whatever is closest (01, or 16) or would it pull the current date?

**Comment by mlandsfeld** [comment]
That looks like it should work! I think we still need to do one for the LST. Here is some code for testing the URL:

#=========  LST ======================

stat = 'data' # 'data ''anomaly' 'z-score'
year = 2021
month = 9
min_pt = [-2128992.283, -4214602.306]
max_pt = [5858710.218, 4615766.178]


if stat == 'data':
    units = 'C'

if stat == 'anomaly':
    units = 'C'

if stat == 'z-score':
    units = 'none'

url = f"https://chc-ewx2.chc.ucsb.edu/proxies/wcsProxy.php?layerNameToUse=lst:"\
      f"lst_africa_1-month-{month:02}-{year}_{units}_{stat}"\
      f"&lowerLeftXToUse={min_pt[0]}&lowerLeftYToUse={min_pt[1]}"\
      f"&upperRightXToUse={max_pt[0]}&upperRightYToUse={max_pt[1]}"\
      f"&wcsURLToUse=https://chc-ewx2.chc.ucsb.edu:8443/geoserver/wcs?"\
      f"&resolution=0.05&srsToUse=EPSG:3857&outputSrsToUse=EPSG:4326"

print("curl '" + url + "' > ~/tmp/cg.tiff")

**Comment by fmdavenport** [comment]
@mlandsfeld Can you also provide template code for CHIRTSMax?  This would be the next priority.  Ideally something that would stay relevant once CHIRTSMax becomes a 'live' product.

**Comment by GoogleSheets** [comment]
> This looks correct to me, but I would want to see how the time series renders in CausMoS. What happens if a user requests the most recent date for CHIRPS-GEFS? Doe is just snap to whatever is closest (01, or 16) or would it pull the current date?

@fmdavenport It will find the month for the most recent date for CHIRPS-GEF, and attempt to pull the 1st and 16th of that month.

**Comment by mlandsfeld** [comment]
@fmdavenport Here is the template code for CHIRTSmax. Note that it was loaded with units = "mm". If this is going to be a. problem with CausMoS let me know and I can reload the dataset with units = "C". This should still work when the updated data is created.


#=========  CHIRTSmax ======================

stat = 'data' # 'data ''anomaly' 'z-score'
year = 2016
month = 9
min_pt = [-2128992.283, -4214602.306]
max_pt = [5858710.218, 4615766.178]


if stat == 'data':
    units = 'mm'   # units should be C

if stat == 'anomaly':
    units = 'mm'   # units should be C

if stat == 'z-score':
    units = 'none'


url = f"https://chc-ewx2.chc.ucsb.edu/proxies/wcsProxy.php?layerNameToUse=chirtsmax:"\
      f"chirtsmax_africa_1-month-{month:02}-{year}_{units}_{stat}"\
      f"&lowerLeftXToUse={min_pt[0]}&lowerLeftYToUse={min_pt[1]}"\
      f"&upperRightXToUse={max_pt[0]}&upperRightYToUse={max_pt[1]}"\
      f"&wcsURLToUse=https://chc-ewx2.chc.ucsb.edu:8443/geoserver/wcs?"\
      f"&resolution=0.05&srsToUse=EPSG:3857&outputSrsToUse=EPSG:4326"

print("curl '" + url + "' > ~/tmp/chirtsmax.tiff")

**Comment by fmdavenport** [comment]
> > This looks correct to me, but I would want to see how the time series renders in CausMoS. What happens if a user requests the most recent date for CHIRPS-GEFS? Doe is just snap to whatever is closest (01, or 16) or would it pull the current date?
> 
> @fmdavenport It will find the month for the most recent date for CHIRPS-GEF, and attempt to pull the 1st and 16th of that month.

That sounds good. Lets stick with that for now as that is the best way to do time series. However we might want a separate registration that only call the latest forecast show that as a raster.

**Pull request merged**
