### PR TITLE
settings + .env

### LINKED ISSUE #20: Convert config.ini to use pydantic settings
config.ini is already being parsed 3x we should switch to using pydantic settings 

Sample Usage/how to

https://fastapi.tiangolo.com/advanced/settings/
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/core/config.py
https://pydantic-docs.helpmanual.io/usage/settings/

### PR DESCRIPTION
**Pull request by scotthaleen**

### CODE REVIEW

**Comment by brandomr** [comment]
This looks great. I love the logging. We need to use that template for future FastAPI projects. It is sweet.

I just updated the README. Should I add a boilerplate `.env` file to `api/.env`. For example:

```
BIND_PORT=8000
ELASTICSEARCH_URL=elasticsearch
ELASTICSEARCH_PORT=9200
DMC_URL=SET_DMC_URL_HERE
DMC_PORT=8080
DMC_USER=jataware
DMC_PASSWORD=wileyhippo
DOJO_URL=http://SET_DOJO_URL_HERE:8000
```

Or this could just be added to the README. Not sure whether there is some issue in having a `.env` file version controlled @scotthaleen

**Review by brandomr — APPROVED** [review]

**Comment by scotthaleen** [comment]
You can override `.env` with `export BIND_PORT=` or whatever.  We could leave the values we want forced to be specified out of the `.env`. I believe pydantic will fail to start if it is missing a field.

**Comment by brandomr** [comment]
Ok I'll add a boilerplate `.env` file and indicate in the README that you can override these values with actual `env` vars. When I tested I didn't set some `env vars` and it did fail nicely and explain what was missing.

**Comment by brandomr** [comment]
> Ok I'll add a boilerplate `.env` file and indicate in the README that you can override these values with actual `env` vars. When I tested I didn't set some `env vars` and it did fail nicely and explain what was missing.

@scotthaleen if that seems ok by you then.... 👍 🚀  to merge

**Pull request merged**
